development:
  adapter: postgresql
  database: ragnarok_development
  pool: 5

test:
  adapter: postgresql
  database: ragnarok__test
  pool: 5

production:
  adapter: postgresql
  database: ragnarok__production
  pool: 5
