development:
  adapter: postgresql
  database: ragnarok_development
  username: username
  password: *****
  pool: 5


test:
  adapter: postgresql
  database: ragnarok__test
  username: username
  password: *****
  pool: 5


production:
  adapter: postgresql
  database: ragnarok__production
  username: username
  password: *****
  pool: 5
